name: linkedin_login_platform_interface
description: "Contains shared logic between platforms and interfaces for them"
version: 3.2.2
publish_to: none
resolution: workspace
homepage: https://github.com/d3xt3r2909/linkedin_login/tree/master/linkedin_login_platform_interface
repository: https://github.com/d3xt3r2909/linkedin_login
documentation:

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  equatable: ^2.0.7
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.26.3
