name: linkedin_login
description: Library for login with LinkedIn OAuth V2 service. This library helps you to implement authorization with LinkedIn OAuth API's.
version: 1.1.1
homepage: https://github.com/d3xt3r2909/linkedin_login
repository: https://github.com/d3xt3r2909/linkedin_login
documentation:
  
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.3.10+1
  http: ^0.12.0+4
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/linked_in_logo.png
