name: linkedin_login
description: Library for login with LinkedIn OAuth V2 service. This library helps you to implement authorization with LinkedIn OAuth API's.
version: 2.2.1
homepage: https://github.com/d3xt3r2909/linkedin_login
repository: https://github.com/d3xt3r2909/linkedin_login
documentation:

environment:
  sdk: '>=2.13.3 <3.0.0'
  flutter: ">=1.24.0-6.0.pre"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  meta: ^1.7.0
  rxdart: ^0.27.3
  uuid: ^3.0.6
  webview_flutter: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  test: ^1.19.5
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/linked_in_logo.png
